version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run: make test


workflows:
  version: 2
  commit:
    jobs:
      - build
